### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Byte

### ISSUE THREAD

**Issue by bunnykek** [eugenelet/Meta-rPPG#26]
```
(py370) C:\Users\bunny\Desktop\Meta-rPPG>py train.py
----------- Networks initialized -------------
Total number of parameters : 0.380 M
---------------------end----------------------
dataset [rPPGDataset-train] was created
dataset [rPPGDataset-test] was created
Data Size: 650 ||||| Batch Size: 3 ||||| initial lr: 0.001000
Traceback (most recent call last):
  File "C:\Users\bunny\Desktop\Meta-rPPG\train.py", line 38, in <module>
    data = dataset[task_list, 0]
  File "C:\Users\bunny\Desktop\Meta-rPPG\data\dataload.py", line 68, in __getitem__
    dat = self.dataset[idx, items[1]]
  File "C:\Users\bunny\Desktop\Meta-rPPG\data\pre_dataload.py", line 97, in __getitem__
    self.baseline_procress(inputs, masks.clone())
  File "C:\Users\bunny\Desktop\Meta-rPPG\data\pre_dataload.py", line 120, in baseline_procress
    mask /= 255
RuntimeError: result type Float can't be cast to the desired output type Byte
```

**Comment by Ding-yd** [comment]
You can try my method
![image](https://github.com/eugenelet/Meta-rPPG/assets/107525557/fc9a18c5-effa-4a8e-abc8-99f599b1aab1)
